#!/bin/sh
tmpfile=$(mktemp)
cat <<EOF >$tmpfile
$(cat ./init.el)

(straight-pull-all)
(straight-rebuild-all)
(straight-freeze-versions)
EOF
emacs --batch -l $tmpfile
rm $tmpfile
git add ./straight/versions
